services:
  jenkins:
    build: .
    networks:
      - jenkins
    ports:
      - "8080:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
      - jenkins-docker-certs:/certs/client:ro
      - ./jenkins.yaml:/var/jenkins_home/jenkins.yaml
    environment:
      - CASC_JENKINS_CONFIG=/var/jenkins_home/jenkins.yaml
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_TLS_VERIFY=1
      - DOCKER_CERT_PATH=/certs/client
  docker:
    image: docker:dind
    networks:
      - jenkins
    privileged: true
    command: --storage-driver=overlay2
    volumes:
      - jenkins_home:/var/jenkins_home
      - jenkins-docker-certs:/certs/client
    environment:
      DOCKER_TLS_CERTDIR: "/certs"
volumes:
  jenkins_home:
  jenkins-docker-certs:
networks:
  jenkins: